## Apex wealth Data Pipeline

In [30]:
pip install requests

Requirement already satisfied: requests in c:\users\mumba\anaconda3\lib\site-packages (2.32.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2025.10.5)
Requirement already satisfied: requests in c:\users\mumba\anaconda3\lib\site-packages (2.32.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2025.10.5)

In [31]:
pip install pandas

Requirement already satisfied: pandas in c:\users\mumba\anaconda3\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.26.0 in c:\users\mumba\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mumba\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mumba\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mumba\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\mumba\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [33]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os

In [34]:
load_dotenv()
api_key = os.getenv('API_KEY')

In [35]:
api_key

'4890cae03d3b43bb8d3631416257da2d'

In [90]:
symbols = "AAPL" 
url = f"https://api.twelvedata.com/time_series?symbol={symbols}&interval=1min&apikey={api_key}&outputsize=20"

In [91]:
# Get response from the API
response = requests.get(url)
response.status_code

200

In [92]:


# get data in json format
from pprint import pprint
data = response.json()
pprint(data)

{'meta': {'currency': 'USD',
          'exchange': 'NASDAQ',
          'exchange_timezone': 'America/New_York',
          'interval': '1min',
          'mic_code': 'XNGS',
          'symbol': 'AAPL',
          'type': 'Common Stock'},
 'status': 'ok',
 'values': [{'close': '259.48001',
             'datetime': '2026-01-30 15:59:00',
             'high': '260.06',
             'low': '258',
             'open': '259.88000',
             'volume': '1973068'},
            {'close': '259.87000',
             'datetime': '2026-01-30 15:58:00',
             'high': '259.93',
             'low': '259.51501',
             'open': '259.60001',
             'volume': '683270'},
            {'close': '259.57001',
             'datetime': '2026-01-30 15:57:00',
             'high': '259.88',
             'low': '259.36499',
             'open': '259.87000',
             'volume': '574705'},
            {'close': '259.85999',
             'datetime': '2026-01-30 15:56:00',
             'high': '260.040009',
             'low': '259.66000',
             'open': '259.82999',
             'volume': '375311'},
            {'close': '259.82999',
             'datetime': '2026-01-30 15:55:00',
             'high': '260.019989',
             'low': '258.89999',
             'open': '259.79999',
             'volume': '603386'},
            {'close': '259.79001',
             'datetime': '2026-01-30 15:54:00',
             'high': '260.089996',
             'low': '259.060089',
             'open': '259.95001',
             'volume': '463393'},
            {'close': '259.95001',
             'datetime': '2026-01-30 15:53:00',
             'high': '260.79001',
             'low': '259.85001',
             'open': '260.76999',
             'volume': '300682'},
            {'close': '260.76901',
             'datetime': '2026-01-30 15:52:00',
             'high': '261.10001',
             'low': '260.59000',
             'open': '261.019989',
             'volume': '407026'},
            {'close': '261.024994',
             'datetime': '2026-01-30 15:51:00',
             'high': '261.49',
             'low': '260.91000',
             'open': '261.41989',
             'volume': '442079'},
            {'close': '261.41000',
             'datetime': '2026-01-30 15:50:00',
             'high': '261.89001',
             'low': '261.38',
             'open': '261.73999',
             'volume': '832226'},
            {'close': '261.79749',
             'datetime': '2026-01-30 15:49:00',
             'high': '261.89990',
             'low': '261.67999',
             'open': '261.69000',
             'volume': '227867'},
            {'close': '261.64001',
             'datetime': '2026-01-30 15:48:00',
             'high': '261.72',
             'low': '261.41',
             'open': '261.43161',
             'volume': '163094'},
            {'close': '261.42001',
             'datetime': '2026-01-30 15:47:00',
             'high': '261.45499',
             'low': '261.25',
             'open': '261.25500',
             'volume': '1284247'},
            {'close': '261.25500',
             'datetime': '2026-01-30 15:46:00',
             'high': '261.37',
             'low': '261.22000',
             'open': '261.34000',
             'volume': '230251'},
            {'close': '261.34000',
             'datetime': '2026-01-30 15:45:00',
             'high': '261.34000',
             'low': '260.95999',
             'open': '260.98001',
             'volume': '266592'},
            {'close': '260.98999',
             'datetime': '2026-01-30 15:44:00',
             'high': '261.03',
             'low': '260.89999',
             'open': '260.91000',
             'volume': '184213'},
            {'close': '260.89999',
             'datetime': '2026-01-30 15:43:00',
             'high': '261.040009',
             'low': '260.76999',
             'open': '260.87000',
             'volume': '237453'},
            {'close': '260.87000',
             'datetime': '2026-01-30 15:42:00',
             'high': '260.98001',
             'low': '260.76001',
             'open': '260.89001',
             'volume': '220712'},
            {'close': '260.90009',
             'datetime': '2026-01-30 15:41:00',
             'high': '261',
             'low': '260.76',
             'open': '260.79001',
             'volume': '235391'},
            {'close': '260.78989',
             'datetime': '2026-01-30 15:40:00',
             'high': '260.89001',
             'low': '260.70001',
             'open': '260.73001',
             'volume': '211636'}]}

In [95]:
data['values'][0] ['high'] # Boana

'260.06'

In [96]:
values = data ['values'] # Chinwendu
first_item = values[0]
high_price = first_item ['high']
high_price

'260.06'

In [98]:
# transfer data to dataframe
def transform_data (data):
    # extract values
    times_series = data['values']

    # covert to dataframe
    df = pd.DataFrame(times_series)

    # convert to proper data types
    df['datetime'] = pd.to_datetime(df['datetime'])

    df = df.astype({ 
        'open': 'float',
        'high':'float',
        'low': 'float', 
        'close': 'float',
        'volume': 'int'
    })

    return df

In [99]:
times_series = data['values']
times_series

[{'datetime': '2026-01-30 15:59:00',
  'open': '259.88000',
  'high': '260.06',
  'low': '258',
  'close': '259.48001',
  'volume': '1973068'},
 {'datetime': '2026-01-30 15:58:00',
  'open': '259.60001',
  'high': '259.93',
  'low': '259.51501',
  'close': '259.87000',
  'volume': '683270'},
 {'datetime': '2026-01-30 15:57:00',
  'open': '259.87000',
  'high': '259.88',
  'low': '259.36499',
  'close': '259.57001',
  'volume': '574705'},
 {'datetime': '2026-01-30 15:56:00',
  'open': '259.82999',
  'high': '260.040009',
  'low': '259.66000',
  'close': '259.85999',
  'volume': '375311'},
 {'datetime': '2026-01-30 15:55:00',
  'open': '259.79999',
  'high': '260.019989',
  'low': '258.89999',
  'close': '259.82999',
  'volume': '603386'},
 {'datetime': '2026-01-30 15:54:00',
  'open': '259.95001',
  'high': '260.089996',
  'low': '259.060089',
  'close': '259.79001',
  'volume': '463393'},
 {'datetime': '2026-01-30 15:53:00',
  'open': '260.76999',
  'high': '260.79001',
  'low': '259.85001',
  'close': '259.95001',
  'volume': '300682'},
 {'datetime': '2026-01-30 15:52:00',
  'open': '261.019989',
  'high': '261.10001',
  'low': '260.59000',
  'close': '260.76901',
  'volume': '407026'},
 {'datetime': '2026-01-30 15:51:00',
  'open': '261.41989',
  'high': '261.49',
  'low': '260.91000',
  'close': '261.024994',
  'volume': '442079'},
 {'datetime': '2026-01-30 15:50:00',
  'open': '261.73999',
  'high': '261.89001',
  'low': '261.38',
  'close': '261.41000',
  'volume': '832226'},
 {'datetime': '2026-01-30 15:49:00',
  'open': '261.69000',
  'high': '261.89990',
  'low': '261.67999',
  'close': '261.79749',
  'volume': '227867'},
 {'datetime': '2026-01-30 15:48:00',
  'open': '261.43161',
  'high': '261.72',
  'low': '261.41',
  'close': '261.64001',
  'volume': '163094'},
 {'datetime': '2026-01-30 15:47:00',
  'open': '261.25500',
  'high': '261.45499',
  'low': '261.25',
  'close': '261.42001',
  'volume': '1284247'},
 {'datetime': '2026-01-30 15:46:00',
  'open': '261.34000',
  'high': '261.37',
  'low': '261.22000',
  'close': '261.25500',
  'volume': '230251'},
 {'datetime': '2026-01-30 15:45:00',
  'open': '260.98001',
  'high': '261.34000',
  'low': '260.95999',
  'close': '261.34000',
  'volume': '266592'},
 {'datetime': '2026-01-30 15:44:00',
  'open': '260.91000',
  'high': '261.03',
  'low': '260.89999',
  'close': '260.98999',
  'volume': '184213'},
 {'datetime': '2026-01-30 15:43:00',
  'open': '260.87000',
  'high': '261.040009',
  'low': '260.76999',
  'close': '260.89999',
  'volume': '237453'},
 {'datetime': '2026-01-30 15:42:00',
  'open': '260.89001',
  'high': '260.98001',
  'low': '260.76001',
  'close': '260.87000',
  'volume': '220712'},
 {'datetime': '2026-01-30 15:41:00',
  'open': '260.79001',
  'high': '261',
  'low': '260.76',
  'close': '260.90009',
  'volume': '235391'},
 {'datetime': '2026-01-30 15:40:00',
  'open': '260.73001',
  'high': '260.89001',
  'low': '260.70001',
  'close': '260.78989',
  'volume': '211636'}]

In [100]:
df = transform_data(data)

In [101]:
df

,datetime,open,high,low,close,volume
0,2026-01-30 15:59:00,259.880000,260.060000,258.000000,259.480010,1973068
1,2026-01-30 15:58:00,259.600010,259.930000,259.515010,259.870000,683270
2,2026-01-30 15:57:00,259.870000,259.880000,259.364990,259.570010,574705
3,2026-01-30 15:56:00,259.829990,260.040009,259.660000,259.859990,375311
4,2026-01-30 15:55:00,259.799990,260.019989,258.899990,259.829990,603386
5,2026-01-30 15:54:00,259.950010,260.089996,259.060089,259.790010,463393
6,2026-01-30 15:53:00,260.769990,260.790010,259.850010,259.950010,300682
7,2026-01-30 15:52:00,261.019989,261.100010,260.590000,260.769010,407026
8,2026-01-30 15:51:00,261.419890,261.490000,260.910000,261.024994,442079
9,2026-01-30 15:50:00,261.739990,261.890010,261.380000,261.410000,832226
10,2026-01-30 15:49:00,261.690000,261.899900,261.679990,261.797490,227867
11,2026-01-30 15:48:00,261.431610,261.720000,261.410000,261.640010,163094
12,2026-01-30 15:47:00,261.255000,261.454990,261.250000,261.420010,1284247
13,2026-01-30 15:46:00,261.340000,261.370000,261.220000,261.255000,230251
14,2026-01-30 15:45:00,260.980010,261.340000,260.959990,261.340000,266592
15,2026-01-30 15:44:00,260.910000,261.030000,260.899990,260.989990,184213
16,2026-01-30 15:43:00,260.870000,261.040009,260.769990,260.899990,237453
17,2026-01-30 15:42:00,260.890010,260.980010,260.760010,260.870000,220712
18,2026-01-30 15:41:00,260.790010,261.000000,260.760000,260.900090,235391
19,2026-01-30 15:40:00,260.730010,260.890010,260.700010,260.789890,211636

##  Extract data for multiple symbols

In [106]:
symbols = [ 'AAPL', 'MSFT', 'GOOGL', 'AMZN' # original symbols requested to be extracted
            'TSLA', 'NVDA', 'NFLX', 'META', 'JPM' # 5 add_symbols 
] 

symbols_str = ",".join(symbols)
url = f"https://api.twelvedata.com/time_series?symbol={symbols_str}&interval=1day&apikey={api_key}&outputsize=20"
response = requests.get(url)
data = response.json()

# all_data =[] commented the below out as the addtion request of the new symbols to be added was hittng the API rate limit. The website allows 8 requests per min but in the meantime we have 9 requests. 

# def fetch_data(symbol, api_key):
    # url = f"https://api.twelvedata.com/time_series?symbol={symbols}&interval=1min&apikey={api_key}&outputsize=50"
    # response = requests.get(url)
    # response.raise_for_status() # this will raise an error for bad responses
    # data = response.json()

    # if data.get('status') != 'ok':
        # raise ValueError(f'Error fetching data for {symbol}:{data.get("message", "Unknown error")}')

    # return data

In [107]:
symbols = [ 'AAPL', 'MSFT', 'GOOGL', 'AMZNTSLA', 'TSLA', 'NVDA', 'NFLX', 'META', 'JPM']

In [109]:

# We are using the batch endpoint to fetch all symbols in one API call.
# This avoids hitting the free-tier rate limit and keeps the workflow simple reason for the loop below and commenting out the fetch_data symbol in symbols code.
# for symbol in symbols:
    # data = fetch_data(symbol, api_key)
    # df = transform_data(data)
    # df['symbol'] = symbol
    # all_data.append(df)

# all_data

all_df = pd.DataFrame()

for symbol in symbols: # Skip symbols missing from the batch response
    if symbol not in data:
        continue

    symbol_data = data[symbol]

    # Skip symbols with no 'values' field
    if "values" not in symbol_data:
        continue

    df = transform_data(symbol_data)
    df['symbol'] = symbol
    all_data.append(df)

In [112]:
# concat - joining or stacking all the dateframes together
all_df = pd.concat(all_data, ignore_index = True)

In [113]:
all_df

      datetime       open       high        low       close    volume symbol
0   2026-01-30  255.17000  261.89999  252.17999  259.480010  92352600   AAPL
1   2026-01-29  258.00000  259.64999  254.41000  258.280000  67253000   AAPL
2   2026-01-28  257.64999  258.85999  254.50999  256.440000  41288000   AAPL
3   2026-01-27  259.17001  261.95001  258.20999  258.269990  49648300   AAPL
4   2026-01-26  251.48000  256.56000  249.80000  255.410000  55969200   AAPL
..         ...        ...        ...        ...         ...       ...    ...
345 2026-01-08  326.39001  331.39999  325.64999  329.790010  11737100    JPM
346 2026-01-07  331.14001  332.14999  324.60001  326.989990   9815200    JPM
347 2026-01-06  332.62000  335.87000  330.64999  334.609990   7660800    JPM
348 2026-01-05  325.50000  337.25000  325.19000  334.040009  10752600    JPM
349 2026-01-02  322.50000  325.73001  320.73999  325.480010   8054000    JPM

[350 rows x 7 columns]

## Loading

In [121]:
load_dotenv()

DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')

In [117]:
pip install psycopg2

Requirement already satisfied: psycopg2 in c:\users\mumba\anaconda3\lib\site-packages (2.9.11)Note: you may need to restart the kernel to use updated packages.

In [122]:
# create database connection url
from sqlalchemy import create_engine
import psycopg2

db_url = f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
engine = create_engine(db_url)


# load datafram to postgres database
all_df.to_sql('stockPrices_data', engine, if_exists='append', index=False)

print('Data Loaded Successfully')

Data Loaded Successfully

In [126]:
# save to csv file
# all_df.to_csv('stock_data.csv', index=False)
all_df.to_csv('stock_add_symbol_data.csv, index=False')