## Apex wealth Data Pipeline

In [4]:
pip install requests

Requirement already satisfied: requests in c:\users\mumba\anaconda3\lib\site-packages (2.32.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2025.10.5)

In [5]:
pip install pandas

Requirement already satisfied: pandas in c:\users\mumba\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mumba\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mumba\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mumba\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mumba\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\mumba\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os

In [7]:
load_dotenv()
api_key = os.getenv('API_KEY')

In [8]:
api_key

'4890cae03d3b43bb8d3631416257da2d'

In [9]:
symbols = "AAPL"
url = f"https://api.twelvedata.com/time_series?symbol={symbols}&interval=1min&apikey={api_key}&outputsize=5"

In [10]:
# Get response from the API
response = requests.get(url)
response.status_code

200

In [11]:


# get data in json format
from pprint import pprint
data = response.json()
pprint(data)

{'meta': {'currency': 'USD',
          'exchange': 'NASDAQ',
          'exchange_timezone': 'America/New_York',
          'interval': '1min',
          'mic_code': 'XNGS',
          'symbol': 'AAPL',
          'type': 'Common Stock'},
 'status': 'ok',
 'values': [{'close': '256.705',
             'datetime': '2026-01-28 15:59:00',
             'high': '256.84',
             'low': '256.67',
             'open': '256.83',
             'volume': '40964'},
            {'close': '256.8',
             'datetime': '2026-01-28 15:58:00',
             'high': '256.84',
             'low': '256.75',
             'open': '256.82',
             'volume': '29319'},
            {'close': '256.84',
             'datetime': '2026-01-28 15:57:00',
             'high': '256.865',
             'low': '256.7',
             'open': '256.7',
             'volume': '41873'},
            {'close': '256.7',
             'datetime': '2026-01-28 15:56:00',
             'high': '256.89',
             'low': '256.7',
             'open': '256.82',
             'volume': '41244'},
            {'close': '256.845',
             'datetime': '2026-01-28 15:55:00',
             'high': '256.85',
             'low': '256.57',
             'open': '256.84',
             'volume': '45419'}]}

In [12]:
data['values'][0] ['high'] # Boana

'256.84'

In [13]:
values = data ['values'] # Chinwendu
first_item = values[0]
high_price = first_item ['high']
high_price

'256.84'

In [14]:
# transfer data to dataframe
def transform_data (data):
    # extract values
    times_series = data['values']

    # covert to dataframe
    df = pd.DataFrame(times_series)

    # convert to proper data types
    df['datetime'] = pd.to_datetime(df['datetime'])

    df = df.astype({ 
        'open': 'float',
        'high':'float',
        'low': 'float', 
        'close': 'float',
        'volume': 'int'
    })

    return df

In [15]:
times_series = data['values']
times_series

[{'datetime': '2026-01-28 15:59:00',
  'open': '256.83',
  'high': '256.84',
  'low': '256.67',
  'close': '256.705',
  'volume': '40964'},
 {'datetime': '2026-01-28 15:58:00',
  'open': '256.82',
  'high': '256.84',
  'low': '256.75',
  'close': '256.8',
  'volume': '29319'},
 {'datetime': '2026-01-28 15:57:00',
  'open': '256.7',
  'high': '256.865',
  'low': '256.7',
  'close': '256.84',
  'volume': '41873'},
 {'datetime': '2026-01-28 15:56:00',
  'open': '256.82',
  'high': '256.89',
  'low': '256.7',
  'close': '256.7',
  'volume': '41244'},
 {'datetime': '2026-01-28 15:55:00',
  'open': '256.84',
  'high': '256.85',
  'low': '256.57',
  'close': '256.845',
  'volume': '45419'}]

In [16]:
df = transform_data(data)

In [17]:
df

             datetime    open     high     low    close  volume
0 2026-01-28 15:59:00  256.83  256.840  256.67  256.705   40964
1 2026-01-28 15:58:00  256.82  256.840  256.75  256.800   29319
2 2026-01-28 15:57:00  256.70  256.865  256.70  256.840   41873
3 2026-01-28 15:56:00  256.82  256.890  256.70  256.700   41244
4 2026-01-28 15:55:00  256.84  256.850  256.57  256.845   45419

##  Extract data for multiple symbols

In [18]:
symbols = [ 'AAPL', 'MSFT', 'GOOGL', 'AMZN']
all_data =[]

def fetch_data(symbol, api_key):
    url = f"https://api.twelvedata.com/time_series?symbol={symbol}&interval=1min&apikey={api_key}&outputsize=5"
    response = requests.get(url)
    response.raise_for_status() # this will raise an error for bad responses
    data = response.json()

    if data.get('status') != 'ok':
        raise ValueError(f'Error fetching data for {symbol}:{data.get("message", "Unknown error")}')

    return data

In [19]:
symbols = [ 'AAPL', 'MSFT', 'GOOGL', 'AMZN']

In [20]:
for symbol in symbols:
    data = fetch_data(symbol, api_key)
    df = transform_data(data)
    df['symbol'] = symbol
    all_data.append(df)

all_data

[             datetime       open       high        low      close  volume  \
 0 2026-01-28 15:59:00  256.82999  256.84000  256.23999  256.44000  583999
 1 2026-01-28 15:58:00  256.82001  256.84000  256.75000  256.82999  340210
 2 2026-01-28 15:57:00  256.70001  256.87000  256.70000  256.80011  155119
 3 2026-01-28 15:56:00  256.82001  256.89999  256.70000  256.70001  131854
 4 2026-01-28 15:55:00  256.84000  256.89999  256.56000  256.81000  151476

   symbol
 0   AAPL
 1   AAPL
 2   AAPL
 3   AAPL
 4   AAPL  ,
              datetime        open        high         low       close  volume  \
 0 2026-01-28 15:59:00  483.015015  483.015015  481.329990  481.720000  522008
 1 2026-01-28 15:58:00  483.049988  483.330000  482.799990  482.989990  324470
 2 2026-01-28 15:57:00  482.079987  483.190000  482.059998  483.010101  201099
 3 2026-01-28 15:56:00  482.029999  482.290010  481.890010  482.059998  150220
 4 2026-01-28 15:55:00  481.200010  482.170010  481.100010  482.010010  129922

   symbol
 0   MSFT
 1   MSFT
 2   MSFT
 3   MSFT
 4   MSFT  ,
              datetime       open       high     low      close  volume symbol
 0 2026-01-28 15:59:00  336.51999  336.64001  335.84  336.14001  580245  GOOGL
 1 2026-01-28 15:58:00  336.42001  336.54999  336.35  336.52499  240499  GOOGL
 2 2026-01-28 15:57:00  336.32001  336.47501  336.17  336.42001  223564  GOOGL
 3 2026-01-28 15:56:00  336.50000  336.51999  336.23  336.29001  187754  GOOGL
 4 2026-01-28 15:55:00  336.78000  336.88000  335.73  336.48499  349896  GOOGL,
              datetime       open       high     low       close   volume  \
 0 2026-01-28 15:59:00  243.24001  243.30000  242.88  243.020004  9346405
 1 2026-01-28 15:58:00  243.18500  243.27000  243.11  243.230000   172287
 2 2026-01-28 15:57:00  243.19000  243.24001  243.11  243.179990   168826
 3 2026-01-28 15:56:00  243.32001  243.35001  243.19  243.190000   112309
 4 2026-01-28 15:55:00  243.58000  243.63000  243.00  243.304990   188554

   symbol
 0   AMZN
 1   AMZN
 2   AMZN
 3   AMZN
 4   AMZN  ]

In [21]:
# concat - joining or stacking all the dateframes together
all_df = pd.concat(all_data, ignore_index = True)

In [22]:
all_df

,datetime,open,high,low,close,volume,symbol
0,2026-01-28 15:59:00,256.829990,256.840000,256.239990,256.440000,583999,AAPL
1,2026-01-28 15:58:00,256.820010,256.840000,256.750000,256.829990,340210,AAPL
2,2026-01-28 15:57:00,256.700010,256.870000,256.700000,256.800110,155119,AAPL
3,2026-01-28 15:56:00,256.820010,256.899990,256.700000,256.700010,131854,AAPL
4,2026-01-28 15:55:00,256.840000,256.899990,256.560000,256.810000,151476,AAPL
5,2026-01-28 15:59:00,483.015015,483.015015,481.329990,481.720000,522008,MSFT
6,2026-01-28 15:58:00,483.049988,483.330000,482.799990,482.989990,324470,MSFT
7,2026-01-28 15:57:00,482.079987,483.190000,482.059998,483.010101,201099,MSFT
8,2026-01-28 15:56:00,482.029999,482.290010,481.890010,482.059998,150220,MSFT
9,2026-01-28 15:55:00,481.200010,482.170010,481.100010,482.010010,129922,MSFT
10,2026-01-28 15:59:00,336.519990,336.640010,335.840000,336.140010,580245,GOOGL
11,2026-01-28 15:58:00,336.420010,336.549990,336.350000,336.524990,240499,GOOGL
12,2026-01-28 15:57:00,336.320010,336.475010,336.170000,336.420010,223564,GOOGL
13,2026-01-28 15:56:00,336.500000,336.519990,336.230000,336.290010,187754,GOOGL
14,2026-01-28 15:55:00,336.780000,336.880000,335.730000,336.484990,349896,GOOGL
15,2026-01-28 15:59:00,243.240010,243.300000,242.880000,243.020004,9346405,AMZN
16,2026-01-28 15:58:00,243.185000,243.270000,243.110000,243.230000,172287,AMZN
17,2026-01-28 15:57:00,243.190000,243.240010,243.110000,243.179990,168826,AMZN
18,2026-01-28 15:56:00,243.320010,243.350010,243.190000,243.190000,112309,AMZN
19,2026-01-28 15:55:00,243.580000,243.630000,243.000000,243.304990,188554,AMZN

## Loading

In [23]:
load_dotenv()

DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')

In [24]:
import os
print(os.getenv("DB_PASSWORD"))

6574

In [29]:
print (DB_USER)

postgres

In [26]:
pip install psycopg2

Requirement already satisfied: psycopg2 in c:\users\mumba\anaconda3\lib\site-packages (2.9.11)Note: you may need to restart the kernel to use updated packages.

In [28]:
# create database connection url
from sqlalchemy import create_engine
import psycopg2

db_url = f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
engine = create_engine(db_url)


# load datafram to postgres database
all_df.to_sql('stockPrices_data', engine, if_exists='append', index=False)

print('Data Loaded Successfully')

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "appex_db" does not exist

(Background on this error at: https://sqlalche.me/e/20/e3q8)