## Apex wealth Data Pipeline

In [30]:
pip install requests

Requirement already satisfied: requests in c:\users\mumba\anaconda3\lib\site-packages (2.32.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2025.10.5)
Requirement already satisfied: requests in c:\users\mumba\anaconda3\lib\site-packages (2.32.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mumba\anaconda3\lib\site-packages (from requests) (2025.10.5)

In [31]:
pip install pandas

Requirement already satisfied: pandas in c:\users\mumba\anaconda3\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.26.0 in c:\users\mumba\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mumba\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mumba\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mumba\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\mumba\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [33]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os

In [34]:
load_dotenv()
api_key = os.getenv('API_KEY')

In [35]:
api_key

'4890cae03d3b43bb8d3631416257da2d'

In [37]:
symbols = "AAPL" 
url = f"https://api.twelvedata.com/time_series?symbol={symbols}&interval=1min&apikey={api_key}&outputsize=5"

In [38]:
# Get response from the API
response = requests.get(url)
response.status_code

200

In [39]:


# get data in json format
from pprint import pprint
data = response.json()
pprint(data)

{'meta': {'currency': 'USD',
          'exchange': 'NASDAQ',
          'exchange_timezone': 'America/New_York',
          'interval': '1min',
          'mic_code': 'XNGS',
          'symbol': 'AAPL',
          'type': 'Common Stock'},
 'status': 'ok',
 'values': [{'close': '259.48001',
             'datetime': '2026-01-30 15:59:00',
             'high': '260.06',
             'low': '258',
             'open': '259.88000',
             'volume': '1973068'},
            {'close': '259.87000',
             'datetime': '2026-01-30 15:58:00',
             'high': '259.93',
             'low': '259.51501',
             'open': '259.60001',
             'volume': '683270'},
            {'close': '259.57001',
             'datetime': '2026-01-30 15:57:00',
             'high': '259.88',
             'low': '259.36499',
             'open': '259.87000',
             'volume': '574705'},
            {'close': '259.85999',
             'datetime': '2026-01-30 15:56:00',
             'high': '260.040009',
             'low': '259.66000',
             'open': '259.82999',
             'volume': '375311'},
            {'close': '259.82999',
             'datetime': '2026-01-30 15:55:00',
             'high': '260.019989',
             'low': '258.89999',
             'open': '259.79999',
             'volume': '603386'}]}

In [40]:
data['values'][0] ['high'] # Boana

'260.06'

In [41]:
values = data ['values'] # Chinwendu
first_item = values[0]
high_price = first_item ['high']
high_price

'260.06'

In [42]:
# transfer data to dataframe
def transform_data (data):
    # extract values
    times_series = data['values']

    # covert to dataframe
    df = pd.DataFrame(times_series)

    # convert to proper data types
    df['datetime'] = pd.to_datetime(df['datetime'])

    df = df.astype({ 
        'open': 'float',
        'high':'float',
        'low': 'float', 
        'close': 'float',
        'volume': 'int'
    })

    return df

In [43]:
times_series = data['values']
times_series

[{'datetime': '2026-01-30 15:59:00',
  'open': '259.88000',
  'high': '260.06',
  'low': '258',
  'close': '259.48001',
  'volume': '1973068'},
 {'datetime': '2026-01-30 15:58:00',
  'open': '259.60001',
  'high': '259.93',
  'low': '259.51501',
  'close': '259.87000',
  'volume': '683270'},
 {'datetime': '2026-01-30 15:57:00',
  'open': '259.87000',
  'high': '259.88',
  'low': '259.36499',
  'close': '259.57001',
  'volume': '574705'},
 {'datetime': '2026-01-30 15:56:00',
  'open': '259.82999',
  'high': '260.040009',
  'low': '259.66000',
  'close': '259.85999',
  'volume': '375311'},
 {'datetime': '2026-01-30 15:55:00',
  'open': '259.79999',
  'high': '260.019989',
  'low': '258.89999',
  'close': '259.82999',
  'volume': '603386'}]

In [44]:
df = transform_data(data)

In [45]:
df

             datetime       open        high        low      close   volume
0 2026-01-30 15:59:00  259.88000  260.060000  258.00000  259.48001  1973068
1 2026-01-30 15:58:00  259.60001  259.930000  259.51501  259.87000   683270
2 2026-01-30 15:57:00  259.87000  259.880000  259.36499  259.57001   574705
3 2026-01-30 15:56:00  259.82999  260.040009  259.66000  259.85999   375311
4 2026-01-30 15:55:00  259.79999  260.019989  258.89999  259.82999   603386

##  Extract data for multiple symbols

In [ ]:
symbols = [ 'AAPL', 'MSFT', 'GOOGL', 'AMZN' # original symbols requested to be extracted
            'TSLA', 'NVDA', 'NFLX', 'META', 'JPM' # 5 add_symbols 
] 

symbols_str = ",".join(symbols)
url = f"https://api.twelvedata.com/time_series?symbol={symbols_str}&interval=1day&apikey={api_key}"
response = requests.get(url)
data = response.json()

# all_data =[] commented the below out as the addtion request of the new symbols to be added was hittng the API rate limit. The website allows 8 requests per min but in the meantime we have 9 requests. 

# def fetch_data(symbol, api_key):
    # url = f"https://api.twelvedata.com/time_series?symbol={symbols}&interval=1min&apikey={api_key}&outputsize=20"
    # response = requests.get(url)
    # response.raise_for_status() # this will raise an error for bad responses
    # data = response.json()

    # if data.get('status') != 'ok':
        # raise ValueError(f'Error fetching data for {symbol}:{data.get("message", "Unknown error")}')

    # return data

In [54]:
symbols = [ 'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NVDA', 'NFLX', 'META', 'JPM']

In [52]:
for symbol in symbols:
    data = fetch_data(symbol, api_key)
    df = transform_data(data)
    df['symbol'] = symbol
    all_data.append(df)

all_data

ValueError: Error fetching data for AAPL:You have run out of API credits for the current minute. 9 API credits were used, with the current limit being 8. Wait for the next minute or consider switching to a higher tier plan at https://twelvedata.com/pricing

In [18]:
# concat - joining or stacking all the dateframes together
all_df = pd.concat(all_data, ignore_index = True)

In [19]:
all_df

,datetime,open,high,low,close,volume,symbol
0,2026-01-28 15:59:00,256.829990,256.840000,256.239990,256.440000,583999,AAPL
1,2026-01-28 15:58:00,256.820010,256.840000,256.750000,256.829990,340210,AAPL
2,2026-01-28 15:57:00,256.700010,256.870000,256.700000,256.800110,155119,AAPL
3,2026-01-28 15:56:00,256.820010,256.899990,256.700000,256.700010,131854,AAPL
4,2026-01-28 15:55:00,256.840000,256.899990,256.560000,256.810000,151476,AAPL
5,2026-01-28 15:59:00,483.015015,483.015015,481.329990,481.720000,522008,MSFT
6,2026-01-28 15:58:00,483.049988,483.330000,482.799990,482.989990,324470,MSFT
7,2026-01-28 15:57:00,482.079987,483.190000,482.059998,483.010101,201099,MSFT
8,2026-01-28 15:56:00,482.029999,482.290010,481.890010,482.059998,150220,MSFT
9,2026-01-28 15:55:00,481.200010,482.170010,481.100010,482.010010,129922,MSFT
10,2026-01-28 15:59:00,336.519990,336.640010,335.840000,336.140010,580245,GOOGL
11,2026-01-28 15:58:00,336.420010,336.549990,336.350000,336.524990,240499,GOOGL
12,2026-01-28 15:57:00,336.320010,336.475010,336.170000,336.420010,223564,GOOGL
13,2026-01-28 15:56:00,336.500000,336.519990,336.230000,336.290010,187754,GOOGL
14,2026-01-28 15:55:00,336.780000,336.880000,335.730000,336.484990,349896,GOOGL
15,2026-01-28 15:59:00,243.240010,243.300000,242.880000,243.020004,9346405,AMZN
16,2026-01-28 15:58:00,243.185000,243.270000,243.110000,243.230000,172287,AMZN
17,2026-01-28 15:57:00,243.190000,243.240010,243.110000,243.179990,168826,AMZN
18,2026-01-28 15:56:00,243.320010,243.350010,243.190000,243.190000,112309,AMZN
19,2026-01-28 15:55:00,243.580000,243.630000,243.000000,243.304990,188554,AMZN

## Loading

In [20]:
load_dotenv()

DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')

In [22]:
import os
print(os.getenv("DB_PASSWORD"))

6574

In [23]:
print (DB_USER)

postgres

In [25]:
pip install psycopg2

Requirement already satisfied: psycopg2 in c:\users\mumba\anaconda3\lib\site-packages (2.9.11)
^C
Note: you may need to restart the kernel to use updated packages.

In [26]:
# create database connection url
from sqlalchemy import create_engine
import psycopg2

db_url = f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
engine = create_engine(db_url)


# load datafram to postgres database
all_df.to_sql('stockPrices_data', engine, if_exists='append', index=False)

print('Data Loaded Successfully')

Data Loaded Successfully

Requirement already satisfied: psycopg2 in c:\users\mumba\anaconda3\lib\site-packages (2.9.11)

In [27]:
# save to csv file
all_df.to_csv('stock_data.csv', index=False)